### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Deckoz2302**
Add Documentation for manually testing ffmpeg streams.

### CODE REVIEW

**Review by cestorer — COMMENTED** [review]
UGH! I should have looked at open PR's! Found this AFTER spending 8 hours trying to debug. Thank you!

**Comment by Deckoz2302** [comment]
If only it was easy to get this merged into the doc's :)

**Comment by sclaflin** [comment]
Life gets in the way of hobbies.  :man_shrugging:

Thanks for the commit!

**Comment by sclaflin** [comment]
Would you mind telling me the make and model of the camera this worked for?

**Comment by Deckoz2302** [comment]
Sure thing. All Dahua, but here are the models
Screenshot_20230818-161449

**Comment by sclaflin** [comment]
Awesome! Thank you!

**Pull request merged**
